def try_me(x):
    if x!= 42:
        raise TypeError("42 is the answer to everything. Try again")
